### ISSUE TITLE
Mixed content errors (from fonts) in Google Chrome

### ISSUE THREAD

**Issue by dcollinsn** [insrcd/PreRegMePublic#4]
`Mixed Content: The page at 'https://prereg.me/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/montserrat/v5/zhcz-_WihjSQC0oHJ9TCYAzyDMXhdD8sAj6OAJTFsBI.woff2'. This request has been blocked; the content must be served over HTTPS.
prereg.me/:1 Mixed Content: The page at 'https://prereg.me/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/montserrat/v5/zhcz-_WihjSQC0oHJ9TCYL3hpw3pgy2gAi-Ip7WPMi0.woff'. This request has been blocked; the content must be served over HTTPS.
prereg.me/:1 Mixed Content: The page at 'https://prereg.me/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/montserrat/v5/IQHow_FEYlDC4Gzy_m8fcmaVI6zN22yiurzcBKxPjFE.woff2'. This request has been blocked; the content must be served over HTTPS.
prereg.me/:1 Mixed Content: The page at 'https://prereg.me/' was loaded over HTTPS, but requested an insecure font 'http://fonts.gstatic.com/s/montserrat/v5/IQHow_FEYlDC4Gzy_m8fcnbFhgvWbfSbdVg11QabG8w.woff'. This request has been blocked; the content must be served over HTTPS.`

When loading https://prereg.me/ using Google Chrome on Windows 10

**Comment by dcollinsn** [comment]
Additional mixed content errors from Dashboard:

`Mixed Content: The page at 'https://prereg.me/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://revox.io/json/min_sales_chart.json'. This request has been blocked; the content must be served over HTTPS.u.send @ d3.v3.js:3u.(anonymous function) @ d3.v3.js:3ca.xhr @ d3.v3.js:3ca.json @ d3.v3.js:5(anonymous function) @ dashboard.js:115j @ jquery-1.11.1.min.js:2k.fireWith @ jquery-1.11.1.min.js:2m.extend.ready @ jquery-1.11.1.min.js:2J @ jquery-1.11.1.min.js:2
d3.v3.js:3 Mixed Content: The page at 'https://prereg.me/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://revox.io/json/charts.json'. This request has been blocked; the content must be served over HTTPS.`

When loading https://prereg.me/dashboard#usa using Google Chrome on Windows 10.

**Comment by insrcd** [comment]
This has been fixed in the next release, thanks.

**Comment by insrcd** [comment]
Cloudflare was caching some of the CSS changes, if you shift-refresh this should be all set.

**Comment by dcollinsn** [comment]
I do still have these ones on the dashboard:

`Mixed Content: The page at 'https://prereg.me/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://revox.io/json/min_sales_chart.json'. This request has been blocked; the content must be served over HTTPS.u.send @ d3.v3.js:3u.(anonymous function) @ d3.v3.js:3ca.xhr @ d3.v3.js:3ca.json @ d3.v3.js:5(anonymous function) @ dashboard.js:115j @ jquery-1.11.1.min.js:2k.fireWith @ jquery-1.11.1.min.js:2m.extend.ready @ jquery-1.11.1.min.js:2J @ jquery-1.11.1.min.js:2
d3.v3.js:3 Mixed Content: The page at 'https://prereg.me/dashboard' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://revox.io/json/charts.json'. This request has been blocked; the content must be served over HTTPS.`

**Comment by insrcd** [comment]
Those are fine, that's just artifacts of the placeholder stuff that's there
and will be removed in a future version.
